  [org.apache.kafka.clients.producer.ProducerConfig]
2020-03-16 02:54:46,042 INFO   ||  Kafka version: 2.4.0   [org.apache.kafka.common.utils.AppInfoParser]
2020-03-16 02:54:46,042 INFO   ||  Kafka commitId: 77a89fcf8d7fa018   [org.apache.kafka.common.utils.AppInfoParser]
2020-03-16 02:54:46,042 INFO   ||  Kafka startTimeMs: 1584327286042   [org.apache.kafka.common.utils.AppInfoParser]
2020-03-16 02:54:46,045 INFO   ||  [Worker clientId=connect-1, groupId=1] Finished starting connectors and tasks   [org.apache.kafka.connect.runtime.distributed.DistributedHerder]
2020-03-16 02:54:46,047 INFO   ||  OracleSourceConnectorConfig values: 
	db.fetch.size = 1
	db.hostname = oracledb
	db.name = testdb
	db.name.alias = test
	db.port = 1521
	db.user = kminer
	db.user.password = kminerpass
	multitenant = false
	parse.dml.data = true
	reset.offset = false
	start.scn = 
	table.blacklist = 
	table.whitelist = test.*
	topic = cdctest
   [com.ecer.kafka.connect.oracle.OracleSourceConnectorConfig]
2020-03-16 02:54:46,047 INFO   ||  Oracle Kafka Connector is starting on test   [com.ecer.kafka.connect.oracle.OracleSourceTask]
2020-03-16 02:54:46,102 INFO   ||  WorkerSourceTask{id=oracle-connector-0} Committing offsets   [org.apache.kafka.connect.runtime.WorkerSourceTask]
2020-03-16 02:54:46,102 INFO   ||  WorkerSourceTask{id=oracle-connector-0} flushing 0 outstanding messages for offset commit   [org.apache.kafka.connect.runtime.WorkerSourceTask]
2020-03-16 02:54:46,102 ERROR  ||  WorkerSourceTask{id=oracle-connector-0} Task threw an uncaught and unrecoverable exception   [org.apache.kafka.connect.runtime.WorkerTask]
org.apache.kafka.connect.errors.ConnectException: Error at database tier, Please check : java.sql.SQLRecoverableException: Listener refused the connection with the following error:
ORA-12514, TNS:listener does not currently know of service requested in connect descriptor
 
	at com.ecer.kafka.connect.oracle.OracleSourceTask.start(OracleSourceTask.java:220)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:208)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-16 02:54:46,102 ERROR  ||  WorkerSourceTask{id=oracle-connector-0} Task is being killed and will not recover until manually restarted   [org.apache.kafka.connect.runtime.WorkerTask]
2020-03-16 02:54:46,102 INFO   ||  Stop called for logminer   [com.ecer.kafka.connect.oracle.OracleSourceTask]
2020-03-16 02:54:46,102 INFO   ||  Logminer session cancel   [com.ecer.kafka.connect.oracle.OracleSourceTask]
2020-03-16 02:54:46,102 WARN   ||  Could not stop task   [org.apache.kafka.connect.runtime.WorkerSourceTask]
java.lang.NullPointerException
	at com.ecer.kafka.connect.oracle.OracleSourceTask.stop(OracleSourceTask.java:298)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.tryStop(WorkerSourceTask.java:196)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.close(WorkerSourceTask.java:154)
	at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:156)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:183)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

